winget install -e --id TIDALMusicAS.TIDAL
winget install -e --id PeterPawlowski.foobar2000
winget install -e --id Microsoft.PowerToys
winget install -e --id Windscribe.Windscribe
winget install -e --id Discord.Discord
winget install -e --id Logitech.GHUB
winget install -e --id Nvidia.GeForceExperience
winget install -e --id Valve.Steam
winget install -e --id Mozilla.Firefox
winget install -e --id Google.Chrome
winget install -e --id Git.Git
winget install -e --id Malwarebytes.Malwarebytes
winget install -e --id subhra74.XtremeDownloadManager
winget install -e --id M2Team.NanaZip
winget install -e --id Notepad++.Notepad++
winget install -e --id Microsoft.VisualStudio.2022.Community
winget install -e --id JetBrains.PyCharm.Community
winget install -e --id JetBrains.IntelliJIDEA.Community
winget install -e --id Microsoft.Sysinternals.ProcessExplorer
winget install -e --id Soulseek.SoulseekQt
winget install -e --id OliverSchwendener.ueli
winget install -e --id REALiX.HWiNFO